### ISSUE TITLE
Docker Compose file refers to a missing start.sh file

### ISSUE THREAD

**Issue by ibnesayeed** [internetarchive/Zeno#175]
The `docker-compose.yml` mounts a [likely local] `start.sh` file and executes that as the main command, but the repo does not contain this file.

```yml
    volumes:
      - ./start.sh:/app/start.sh
      - ./jobs:/app/jobs
    command: [ "/bin/sh", "/app/start.sh" ]
```
